config/routes.rb
Rails.application.routes.draw do
  resources :product_variants
  resources :products
  root 'products#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/product.rb
class Product < ApplicationRecord
    has_many :product_variants
    accepts_nested_attributes_for :product_variants, allow_destroy: true
end

app/models/product_variant.rb
class ProductVariant < ApplicationRecord
  belongs_to :product
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/product_variants_controller.rb
class ProductVariantsController < ApplicationController
  before_action :set_product_variant, only: %i[ show edit update destroy ]

  # GET /product_variants or /product_variants.json
  def index
    @product_variants = ProductVariant.all
  end

  # GET /product_variants/1 or /product_variants/1.json
  def show
  end

  # GET /product_variants/new
  def new
    @product_variant = ProductVariant.new
  end

  # GET /product_variants/1/edit
  def edit
  end

  # POST /product_variants or /product_variants.json
  def create
    @product_variant = ProductVariant.new(product_variant_params)

    respond_to do |format|
      if @product_variant.save
        format.html { redirect_to @product_variant, notice: 'Product variant was successfully created.' }
        format.json { render :show, status: :created, location: @product_variant }
      else
        format.html { render :new }
        format.json { render json: @product_variant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /product_variants/1 or /product_variants/1.json
  def update
    respond_to do |format|
      if @product_variant.update(product_variant_params)
        format.html { redirect_to @product_variant, notice: 'Product variant was successfully updated.' }
        format.json { render :show, status: :ok, location: @product_variant }
      else
        format.html { render :edit }
        format.json { render json: @product_variant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /product_variants/1 or /product_variants/1.json
  def destroy
    @product_variant.destroy
    respond_to do |format|
      format.html { redirect_to product_variants_url, notice: 'Product variant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product_variant
      @product_variant = ProductVariant.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_variant_params
      params.require(:product_variant).permit(:color, :size, :product_id)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]

  # GET /products or /products.json
  def index
    @products = Product.all
  end

  # GET /products/1 or /products/1.json
  def show
    print( params[ :confirm ] )
  end

  # GET /products/new
  def new
    @product = Product.new
    @product.product_variants.build
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy
    puts( "here" )
    print(@product)
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:title, :description,  product_variants_attributes: [:id, :color, :size])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper


    def link_to_add_fields(name, f, association)
     ## create a new object from the association (:product_variants)
     new_object = f.object.send(association).klass.new
 
     ## just create or take the id from the new created object
     id = new_object.object_id
 
     ## create the fields form
     fields = f.fields_for(association, new_object, child_index: id) do |builder|
         render(association.to_s.singularize + "_fields", f: builder)
     end
     ## pass down the link to the fields form
     link_to(name, '#', class: 'add_fields', data: {id: id, fields: fields.gsub("\n", "")})
 
    end
 end

app/helpers/product_variants_helper.rb
module ProductVariantsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NestedForms</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script type="text/javascript" src="https://code.jquery.com/jquery.min.js"></script>
    
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/product_variants/_form.html.erb
<%= form_with(model: product_variant, local: true) do |form| %>
  <% if product_variant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product_variant.errors.count, "error") %> prohibited this product_variant from being saved:</h2>

      <ul>
      <% product_variant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :color %>
    <%= form.text_field :Color %>
  </div>

  <div class="field">
    <%= form.label :size %>
    <%= form.text_field :Size %>
  </div>

  <div class="field">
    <%= form.label :product_id %>
    <%= form.text_field :product_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/product_variants/edit.html.erb
<h1>Editing Product Variant</h1>

<%= render 'form', product_variant: @product_variant %>

<%= link_to 'Show', @product_variant %> |
<%= link_to 'Back', product_variants_path %>

app/views/product_variants/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Product Variants</h1>

<table>
  <thead>
    <tr>
      <th>Color</th>
      <th>Size</th>
      <th>Product</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @product_variants.each do |product_variant| %>
      <tr>
        <td><%= product_variant.Color %></td>
        <td><%= product_variant.Size %></td>
        <td><%= product_variant.product %></td>
        <td><%= link_to 'Show', product_variant %></td>
        <td><%= link_to 'Edit', edit_product_variant_path(product_variant) %></td>
        <td><%= link_to 'Destroy', product_variant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product Variant', new_product_variant_path %>

app/views/product_variants/new.html.erb
<h1>New Product Variant</h1>

<%= render 'form', product_variant: @product_variant %>

<%= link_to 'Back', product_variants_path %>

app/views/product_variants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Color:</strong>
  <%= @product_variant.Color %>
</p>

<p>
  <strong>Size:</strong>
  <%= @product_variant.Size %>
</p>

<p>
  <strong>Product:</strong>
  <%= @product_variant.product %>
</p>

<%= link_to 'Edit', edit_product_variant_path(@product_variant) %> |
<%= link_to 'Back', product_variants_path %>

app/views/products/_form.html.erb
<%= form_for @product do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Title %>
    <%= form.text_field :Title %>
  </div>

  <div class="field">
    <%= form.label :Description %>
    <%= form.text_field :Description %>
  </div>

  <div class="field">

    <%= form.fields_for :product_variants do |f| %>
      <%= render 'product_variant_fields', f: f %>
    <% end %>
  <%= link_to_add_fields "Add Variant", form, :product_variants %>
   
  </div>




  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<script>

$('form').on('click', '.remove-fields', function(event) {
  console.log('clicked')
    $(this).prev('input[type=hidden]').val('1');
    $(this).closest('fieldset').hide();
    return event.preventDefault();
  });

$('form').on('click', '.add_fields', function(event) {
    console.log('clicked!')
     var regexp, time;
     time = new Date().getTime();
     regexp = new RegExp($(this).data('id'), 'g');
     $(this).before($(this).data('fields').replace(regexp, time));
     return event.preventDefault();
    });
</script>

app/views/products/_product_variant_fields.html.erb
<fieldset>
<%= f.label :Color %>
<%= f.text_field :Color %>

<%= f.label :Size %>
<%= f.text_field :Size %>
<%= f.hidden_field :_destroy %>
<%= link_to "remove", '#', class: "remove_fields" %>
</fieldset>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.Title %></td>
        <td><%= product.Description %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
   </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

<script>

  

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @product.Title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.Description %>
</p>

<p>
  <strong>Available Variants: <%= @product.product_variants.count %>  </strong>
</p>

<% @product.product_variants.each do |variant|  %>
<p>
  

  <%= variant.Color %>
  <%= variant.Size %>


</p>

<% end %>
<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>